export interface SurveyInput {
    // ID is generated by mongoDB for inputs
    publish: boolean;
    name: string;
    range: number;
    cols: number[];
    statements: string[];
    users: User[];
}

export interface Survey {
    _id: string;
    publish: boolean;
    name: string;
    range: number;
    cols: number[];
    statements: string[];
    users: User[];
}

export interface User {
    _id: string;
    register: {
        age: string;
        gender: string;
        main_lang: string;
        other_lang: string;
    };
    progress: number;
    questions_ans: string[];
    sort_agree: number[];
    sort_neutral: number[];
    sort_disagree: number[];
    matrix: number[][];
}

export const GridTemplates = [
    { label: '+3 to -3', val: '7', default_cols: [2, 3, 4, 5, 4, 3, 2]},
    { label: '+4 to -4', val: '9', default_cols: [2, 3, 4, 5, 6, 5, 4, 3, 2]},
    { label: '+5 to -5', val: '11', default_cols: [2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2]}
];
